export const GROUND_TRUTH_OUTFITS = [
  { stil: 'casual', parcalar: [546, 537, 656, 766, 678] },
  { stil: 'office', parcalar: [113, 566, 812, 683, 638] },
  { stil: 'office', parcalar: [282, 552, 786, 336, 701, 664] },
  { stil: 'chic', parcalar: [148, 754, 601, 708] },
  { stil: 'chic', parcalar: [184, 814, 609, 685] },
  { stil: 'formal', parcalar: [526, 523, 603, 710] },
  { stil: 'school', parcalar: [67, 431, 614, 767, 681] },
  { stil: 'party', parcalar: [185, 427, 803, 616, 723, 722] },
  { stil: 'party', parcalar: [569, 255, 18, 375, 673, 716] },
  { stil: 'party', parcalar: [133, 802, 609, 722, 723] },
];

export const COLOR_MATCH_MAP: Record<string, string[]> = {
  black: [
    'black',
    'white',
    'grey',
    'gray',
    'beige',
    'cream',
    'red',
    'blue',
    'navy',
    'dark blue',
    'gold',
    'silver',
    'green',
  ],
  white: [
    'white',
    'black',
    'grey',
    'gray',
    'beige',
    'cream',
    'blue',
    'denim',
    'navy',
    'dark blue',
    'gold',
    'silver',
    'green',
  ],
  green: ['black', 'white'],
  navy: ['navy', 'dark blue', 'blue', 'white', 'grey', 'gray', 'beige', 'cream'],
  'dark blue': ['navy', 'dark blue', 'blue', 'white', 'grey', 'gray', 'beige', 'cream'],
  blue: ['blue', 'navy', 'dark blue', 'white', 'grey', 'gray', 'denim'],
  denim: ['denim', 'white', 'black', 'grey', 'blue'],
  beige: ['beige', 'cream', 'white', 'black', 'brown', 'khaki', 'natural'],
  natural: ['natural', 'beige', 'cream', 'white', 'black', 'brown'],
  cream: ['cream', 'beige', 'white', 'black', 'brown'],
  brown: ['brown', 'beige', 'cream', 'black', 'khaki', 'natural'],
  grey: ['grey', 'gray', 'white', 'black', 'navy', 'dark blue', 'blue'],
  gray: ['gray', 'grey', 'white', 'black', 'navy', 'dark blue', 'blue'],
  gold: ['gold', 'black', 'white', 'cream', 'beige', 'green', 'red'],
  silver: ['silver', 'black', 'white', 'grey', 'gray', 'blue', 'green'],
};
